#LuckPermChatFormater
#By IndianPL
# <msg> - player message
# <suffix> - player group suffic
# <player> - player name
# <prefix> - player group prefix
message.format: "<prefix> <player> <suffix> » <msg>"