#LuckPermChatFormater
#By IndianPL
# <msg> - player message
# <suffix> - player group suffix
# <player> - player name
# <prefix> - player group prefix
# <name> - player name
# <health> - player health
# <device> - player device
# <model> - device model
# <version> - Minecraft version
# <language> - player Language
# <ping> - player ping

#Formater
message.format: "<prefix> <player> <suffix> » <msg>"
#Censorship
#CenzorShip remove all Upper words
enable-censorship: true
censorship: "Bread"
BlackWords:
  - "dupa"
  - "fuck"
  - "nab"
  - "ez"
#Cooldown
cooldown-enable: true
cooldown: 5
cooldown-message: "§aYou must wait §b <left>§eSeconds§a!"

#Os
Windows: "§f[§bWindows§f]"
Android: "§f[§aAndroid§f]"
Ios: "§f[§bIos§f]"
Mac: "§f[§cMac Os§f]"
Fire: "§f[§6Fire Os§f]"
Gearvr: "§f[§aGearVr§f]"
Hololens: "§f[§aHoloLens§f]"
Dedicated: "§f[§aDedicated§f]"
TvOs: "§f[§aTvOs§f]"
PlayStation: "§f[§aPS§f]"
Nintendo: "§f[§aNintedno§f]"
Xbox: "§f[§aXbox§f]"
Unknow: "§f[§aUnknow§f]"